Yandex map with search
E87EHUU/MyPet pull request #8
Opened 2023-11-08 06:27 UTC by Esfimus

2023-11-08 08:08 UTC, zfix27r requested changes

2023-11-08 08:08 UTC, zfix27r commented on app/src/main/java/com/example/mypet/ui/map/MapFragment.kt
> +        fun newInstance() = MapFragment()
Это при каждом обращение создается новый экземпляр фрагмента? а зачем?

2023-11-09 05:29 UTC, Esfimus commented on app/src/main/java/com/example/mypet/ui/map/MapData.kt
> +data class MapUiState(
Готово, все модели разделили и перенес.

2023-11-09 05:32 UTC, Esfimus commented on app/src/main/java/com/example/mypet/ui/map/MapFragment.kt
> +    @Deprecated("Deprecated in Java")
Порядок, подавления убрал.

2023-11-09 05:39 UTC, Esfimus commented on app/src/main/java/com/example/mypet/ui/map/MapFragment.kt
> +    @Suppress("DEPRECATION")
Сделано

2023-11-09 05:40 UTC, Esfimus commented on app/src/main/java/com/example/mypet/ui/map/MapFragment.kt
> +    private var _ui: FragmentMapBinding? = null
Не знаком с этой библиотекой, исправил по аналогии, работает. Дестроить binding не нужно при этом?

2023-11-09 05:48 UTC, Esfimus commented on app/src/main/java/com/example/mypet/ui/map/MapFragment.kt
> +    private fun View.snackMessage(text: String, length: Int = Snackbar.LENGTH_SHORT) {
Готово

2023-11-09 06:00 UTC, Esfimus commented on app/src/main/java/com/example/mypet/ui/pet/detail/PetDetailFragment.kt
> +
Это новое для меня, исправил, работает хорошо.

2023-11-09 06:19 UTC, Esfimus commented on app/src/main/res/layout/fragment_map.xml
> +        android:id="@+id/mapView"
Исправлено

2023-11-09 06:21 UTC, Esfimus commented on app/src/main/res/values/dimens.xml
> +    <dimen name="mapButtonSize">60dp</dimen>
Исправлено

2023-11-09 06:23 UTC, Esfimus commented on app/src/main/res/values/strings.xml
> +    <string name="zoomOut">Zoom out</string>
Исправлено

2023-11-09 06:32 UTC, Esfimus commented on app/src/main/res/values/strings.xml
> +    <string name="ok">OK</string>
все переименовал

2023-11-09 06:33 UTC, Esfimus commented on build.gradle.kts
> +        classpath("com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:2.0.1")
Да, эта библиотека нужна, потому что с ее помощью прячется апи ключ в local.properties. Возможно, есть и другие решения, но эта библиотека современная и рекомендуется гуглом. С ее помощью при декомпиляции приложения невозможно восстановить ключ.

2023-11-09 06:35 UTC, Esfimus commented on app/src/main/java/com/example/mypet/ui/map/MapFragment.kt
> +        fun newInstance() = MapFragment()
Уже убрал при переходе на навигацию. А вообще так научили создавать и использовать фрагменты.

2023-11-09 07:21 UTC, zfix27r commented on app/src/main/java/com/example/mypet/ui/map/MapFragment.kt
> +    private var _ui: FragmentMapBinding? = null
Нет, биндинг привязывается к жизненному циклу фрагмента.

2023-11-09 07:41 UTC, zfix27r approved these changes

2023-11-09 07:41 UTC, zfix27r commented on app/src/main/java/com/example/mypet/domain/UiExtension.kt
> +package com.example.mypet.domain
Тут смысл функции расширения выносить в отдельный файл.
UIExtension - подразумевает что это расширения для ui слоя, а у вас он в domain

2023-11-09 07:41 UTC, zfix27r commented on app/src/main/res/layout/fragment_pet_detail.xml
> +        android:id="@+id/mapButton"
в данном случае кнопка уже привязано к pet_detail

2023-11-09 07:41 UTC, zfix27r commented on app/src/main/java/com/example/mypet/ui/map/MapFragment.kt
> +    companion object {
Обычно статик блок располагают в начале или в конце класса. Просто наблюдение.

2023-11-10 13:26 UTC, merged